### ISSUE TITLE
Scaffold package

### ISSUE THREAD

**Issue by Planeshifter** [stdlib-js/scaffold-pkg-pr-action#1]
```yaml
action: scaffold
package: assert/is-current-year
alias: isCurrentYear
CLI: true
```

```js
/**
* Tests if a value is either an integer equal to the current year or a `Date` object representing the current year.
*
* @param {*} value - value to test
* @returns {boolean} boolean indicating whether value is the current year
*
* @example
* var bool = isCurrentYear( new Date() );
* // returns true
*
* @example
* var currentYear = require( '@stdlib/time-current-year' );
* var bool = isCurrentYear( currentYear() );
* // returns true
*
* @example
* var bool = isCurrentYear( 2021 );
* // returns false
*
* @example
* var bool = isCurrentYear( null );
* // returns false
*/
```
